# Generated by Django 5.1.6 on 2025-04-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_id",
            field=models.CharField(blank=True, null=True, verbose_name="Telegram ID"),
        ),
    ]
