# Generated by Django 5.1.6 on 2025-05-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_tg_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tg_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Telegram ID"
            ),
        ),
    ]
