# Generated by Django 5.1.6 on 2025-04-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0003_alter_habit_action_alter_habit_frequency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="tg_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
