# Generated by Django 5.1.6 on 2025-04-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0004_habit_tg_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Привычка"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True, help_text="Время на выполнение в минутах", null=True
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.PositiveIntegerField(
                blank=True, default=1, null=True, verbose_name="Периодичность"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Приятная привычка"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Статус публичности"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Место выполнения"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Во сколько выполнять привычку?"
            ),
        ),
    ]
