# Generated by Django 5.1.6 on 2025-05-09 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0005_alter_habit_action_alter_habit_duration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatedHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "habit",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_to",
                to="habit.relatedhabit",
            ),
        ),
    ]
