name: Django

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8
        run: flake8 .

  test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Перейти в директорию проекта
        run: |
          cd ./MyProjects/Habit

      - name: Установить PYTHONPATH
        run: |
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Set environment variables for testing
        env:
          TESTING: '1'
        run: echo "TESTING=1" >> $GITHUB_ENV

      - name: Start PostgreSQL in Docker
        run: |
          docker run -d --name postgres-test -e POSTGRES_PASSWORD=fv4202QAZ -e POSTGRES_DB=postgres -p 5432:5432 postgres:16
          sleep 15

      - name: Set environment variables for Django
        run: |
          echo "DJANGO_SETTINGS_MODULE=Habit.settings" >> $GITHUB_ENV
          echo "DATABASE_URL=postgres://postgres:fv4202QAZ@localhost:5432/postgres" >> $GITHUB_ENV

      - name: Выполнить миграции
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          TESTING: '1'
        run: |
          cd Z:/MyProjects/Habit
          python manage.py migrate

      - name: Запустить тесты
        env:
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
        run: |
          cd Z:/MyProjects/Habit
          python manage.py test --noinput

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Создать .env файл
        run: |
          touch .env
          echo '"${{ secrets.SECRET_KEY }}"' | sed "s/\"//g" > .env

      - name: Войти в Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Построить Docker-образы
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_HUB_USERNAME }}/habit-tracker:latest .
          docker build --no-cache -t ${{ secrets.DOCKER_HUB_USERNAME }}/habit-tracker-nginx:latest nginx/.
          docker build --no-cache -t ${{ secrets.DOCKER_HUB_USERNAME }}/celeri-worker:latest .
          docker build --no-cache -t ${{ secrets.DOCKER_HUB_USERNAME }}/celeri-beat:latest .

      - name: Отправить образы в Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/habit-tracker:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/habit-tracker-nginx:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/celeri-worker:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/celeri-beat:latest

  copy_files_in_server:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Создать .env файл
        run: |
          touch .env
          echo '"${{ secrets.ENV_FILE }}"' | sed "s/\"//g" > .env

      - name: Копировать файлы
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY_PRIVATE }}
          source: "docker-compose.yml,.env"
          target: ${{ secrets.DEPLOY_DIR }}

  run_server:
    needs: [build, copy_files_in_server]
    runs-on: ubuntu-latest

    steps:
      - name: Настроить SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE }}

      - name: Выполнить команды через SSH
        env:
          DEBUG: True
        run: |
          ssh -o StrictHostKeyChecking=no -vT ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd "${{ secrets.DEPLOY_DIR }}"
          
            # Остановить все контейнеры
            sudo docker ps -aq | xargs -r sudo docker rm -f
          
            # Удалить все образы, связанные с проектом
            sudo docker images -q | xargs -r sudo docker rmi -f
          
            # Очистить все неиспользуемые данные
            sudo docker system prune -f --volumes
          
            # Обновить образы из Docker Hub
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/habit-tracker:latest
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/habit-tracker-nginx:latest
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/celeri-worker:latest
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/celeri-beat:latest
          
            # Запустить контейнеры
            sudo docker compose up -d --build
          EOF
